[package]
name = "rust5inarow"
version = "0.1.0"
authors = ["kumm <kumm@webstar.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.6.0"
